name: Manual Trigger
on:
  workflow_dispatch:
    inputs:
      express-api-branch: 
        type: choice
        description: choose the express-api app branch
        options:
          - main
          - work-bench
      test-type: 
        type: choice
        description: choose the type of tests to run
        options:
          - api_demo
          - ui_demo
          - demo
jobs:
  run-automation:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Clone express-api-demo app
        run: git clone -b ${{github.event.inputs.express-api-branch}} http://github.com/Srinivasaimandi/express-api-demo.git

      - name: Install and start server
        run: |
          cd express-api-demo
          npm install
          npm start &
          echo "API server started"
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npx playwright test --project ${{github.event.inputs.test-type}}
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: my-report
          path: my-report/
          retention-days: 30
