name: Test Trigger
on:
  workflow_dispatch:
    inputs:
      name: 
        type: choice
        description: choose the type of tests to run
        options:
          - api_demo
          - ui_demo
          - demo
jobs:
  run-automation:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Clone express-api-demo
      run: git clone http://github.com/Srinivasaimandi/express-api-demo.git
    - name: Install and start server
      run: |
        cd express-api-demo
        npm install
        npm start

    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      run: npx playwright test --project ${{github.event.inputs.name}}
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: my-report
        path: my-report/
        retention-days: 30

    

  
